[package]
name = "tagid-derive"
version = "1.1.0"
edition = "2021"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
description = "Defines a derive macro for the tagid newtype labeled tagging for different types of ids."
license = "MIT"
repository = "https://github.com/dmrolfs/tagid-rs"
homepage = "https://github.com/dmrolfs/tagid-rs"
documentation = "https://docs.rs/tagid"
readme = "README.md"
keywords = ["identifier", "id", "cuid", "snowflake", "uuid"]
categories = ["data-structures", "development-tools"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true